/// OptimizerPass — interface and context for multi-pass team spec generation.
///
/// The optimizer runs TeamSpec generation in ordered passes. Earlier passes are
/// fast (minutes) and find obvious solutions; later passes expand the search
/// space progressively (hours, then days). Each unique TeamSpec is simulated at
/// most once across all passes — the engine deduplicates by canonical hash.
///
/// Pass ordering (fastest to slowest):
///   1. PatternPass  — replay prior clearing runs from RunHistory
///   2. RulesPass    — current CandidateConverter (6 enumerated dimensions)
///   3. BruteForcePass — {T1,T2,T3} enumeration per non-battery skill
///
/// See notes/design_decisions.md §"Multi-Pass Optimizer Architecture".
library;

import 'package:chaldea/models/models.dart';

import '../roster/run_history.dart';
import '../roster/user_roster.dart';
import '../search/enumerator.dart';
import '../simulation/headless_runner.dart';

// ---------------------------------------------------------------------------
// PassContext
// ---------------------------------------------------------------------------

/// All inputs a pass may need to generate TeamSpecs.
///
/// Passes should only read from this context — they do not modify it.
/// The engine owns [candidates] (pre-generated once before any pass runs)
/// so all passes work from the same candidate set.
class PassContext {
  /// The quest being optimised for.
  final QuestPhase quest;

  /// The player's roster (servants, CEs, MCs).
  final UserRoster roster;

  /// All candidate team compositions generated by the Enumerator.
  /// Pre-generated once and shared across all passes.
  final List<CandidateTeam> candidates;

  /// Prior clearing runs recorded to disk, or null if no history file exists yet.
  /// Used by PatternPass to replay known-good teams on the current quest.
  final RunHistory? history;

  const PassContext({
    required this.quest,
    required this.roster,
    required this.candidates,
    this.history,
  });
}

// ---------------------------------------------------------------------------
// OptimizerPass
// ---------------------------------------------------------------------------

/// Abstract base for a single optimizer pass.
///
/// Implement [generate] to yield [TeamSpec]s. The engine deduplicates by
/// canonical hash before simulating, so passes do not need to track what
/// prior passes have already generated.
abstract class OptimizerPass {
  /// Human-readable name shown in progress/logging output.
  String get name;

  /// Yields [TeamSpec]s to be simulated by the engine.
  ///
  /// Called once per engine run. The engine collects specs from this stream,
  /// skips any whose canonical hash was already simulated, and runs the rest.
  Stream<TeamSpec> generate(PassContext ctx);
}
